Repository galaxyproject/brc-analytics, pull requests merged in 2025-09, with the labels that each got.

#768 feat: set up ga2 site config (#751)
  app/apis/catalog/brc-analytics-catalog/common/utils.ts
  app/components/Entity/components/AnalysisMethodsCatalog/utils.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/hooks/UseUCSCFiles/hook.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/hooks/UseENADataByTaxonomyId/hook.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/types.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/types.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/types.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/SideColumn/types.ts
  app/config/config.ts
  app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
  app/viewModelBuilders/catalog/ga2/viewModelBuilders.ts
  app/views/EntityView/entityView.tsx
  app/views/HomeView/ga2/homeView.tsx
  app/views/WorkflowInputsView/types.ts
  package.json
  pages/about/index.tsx
  pages/calendar/index.tsx
  pages/data/[entityListType]/[entityId]/[trsId]/index.tsx
  pages/data/[entityListType]/[entityId]/index.tsx
  pages/data/[entityListType]/index.tsx
  pages/index.tsx
  pages/roadmap/index.tsx
  public/logo/galaxy.png
  site-config/brc-analytics/dev/config.ts
  site-config/brc-analytics/local/config.ts
  site-config/brc-analytics/local/index/genomeEntityConfig.ts
  site-config/brc-analytics/local/index/organismEntityConfig.ts
  site-config/brc-analytics/local/index/priorityPathogensEntityConfig.ts
  site-config/brc-analytics/prod/config.ts
  site-config/common/constants.ts
  site-config/common/entities.ts
  site-config/ga2/category.ts
  site-config/ga2/dev/.env
  site-config/ga2/dev/config.ts
  site-config/ga2/images/favicons/android-chrome-192x192.png
  site-config/ga2/images/favicons/android-chrome-512x512.png
  site-config/ga2/images/favicons/apple-touch-icon.png
  site-config/ga2/images/favicons/favicon-16x16.png
  site-config/ga2/images/favicons/favicon-32x32.png
  site-config/ga2/images/favicons/favicon.ico
  site-config/ga2/images/favicons/site.webmanifest
  site-config/ga2/local/.env
  site-config/ga2/local/config.ts
  site-config/ga2/local/entity/genome/analysisMethodMainColumn.ts
  site-config/ga2/local/entity/genome/analysisMethodsSideColumn.ts
  site-config/ga2/local/entity/genome/analysisMethodsTop.ts
  site-config/ga2/local/entity/organism/organismMainColumn.ts
  site-config/ga2/local/entity/organism/organismTop.ts
  site-config/ga2/local/index/common/category/categoryConfig.ts
  site-config/ga2/local/index/common/category/categoryRegistry.ts
  site-config/ga2/local/index/genome/categoryGroups.ts
  site-config/ga2/local/index/genome/columnDefs.ts
  site-config/ga2/local/index/genome/columns.ts
  site-config/ga2/local/index/genome/genomeEntityConfig.ts
  site-config/ga2/local/index/organism/categoryGroups.ts
  site-config/ga2/local/index/organism/columnDefs.ts
  site-config/ga2/local/index/organism/columns.ts
  site-config/ga2/local/index/organism/organismEntityConfig.ts
  site-config/ga2/prod/.env
  site-config/ga2/prod/config.ts
Labels: feat

#823 feat: configure export as tsv to select sequencing runs table (#731)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.styles.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/hook.ts
Labels: feat

#844 feat: add socials to header navigation menu for mid-sized viewports (#842)
  site-config/brc-analytics/local/config.ts
  site-config/brc-analytics/local/socialMedia.ts
Labels: feat

#853 feat: update stepper ui for large number of sequences in the final step (#852)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.styles.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.tsx
Labels: feat

#843 feat: handle mislabeled paired-end read runs on ena picker (#801)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/Table/components/TableCell/components/BasicCell/basicCell.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/dataTransforms.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/hook.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/utils.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/types.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/sequencingStep.tsx
  package-lock.json
  package.json
Labels: feat

#866 feat: implemented code to re-create tanonomy read_run count file
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/hooks/UseENADataByTaxonomyId/taxonomy_read_counts.json
  catalog/ga2/build/intermediate/taxId.json
  catalog/ga2/build/py/build_files_from_ncbi.py
  catalog/py_package/catalog_build/__init__.py
  catalog/py_package/catalog_build/build.py
Labels: feat, GA2, ga2 roadmap item

#870 feat: [ga2] select / create a logo (#756)
  app/components/Home/components/Section/components/SectionAnalytics/components/AnalyticsTools/analyticsTools.tsx
  app/components/Home/components/Section/components/ga2/SectionAnalyticsAndData/components/AnalyticsToolsAndData/analyticsToolsAndData.styles.ts
  app/components/Home/components/Section/components/ga2/SectionAnalyticsAndData/components/AnalyticsToolsAndData/analyticsToolsAndData.tsx
  app/components/Home/components/Section/components/ga2/SectionHero/components/Carousel/carousel.styles.ts
  app/components/Home/components/Section/components/ga2/SectionHero/components/Carousel/carousel.tsx
  app/components/Home/components/Section/components/ga2/SectionHero/components/Carousel/components/Arrow/arrow.tsx
  app/components/Home/components/Section/components/ga2/SectionHero/components/Carousel/hooks/useInteractiveCarousel.ts
  app/components/Home/components/Section/components/ga2/SectionSubHero/sectionSubHero.styles.ts
  app/components/common/Bullets/bullets.tsx
  app/theme/common/palette.ts
  public/logo/ga2.svg
  public/logo/galaxy.png
  public/main/chose-genome-assembly-ga2.png
  public/main/select-an-organism-ga2.png
  public/main/select-analysis-workflow-data-ga2.png
  public/main/select-analysis-workflow-ga2.png
  site-config/brc-analytics/local/config.ts
  site-config/brc-analytics/local/theme/constants.ts
  site-config/ga2/images/favicons/android-chrome-192x192.png
  site-config/ga2/images/favicons/android-chrome-512x512.png
  site-config/ga2/images/favicons/apple-touch-icon.png
  site-config/ga2/images/favicons/favicon-16x16.png
  site-config/ga2/images/favicons/favicon-32x32.png
  site-config/ga2/images/favicons/favicon.ico
  site-config/ga2/local/config.ts
  site-config/ga2/local/theme/constants.ts
Labels: feat

#744 fix: workflow published version validation
  catalog/output/workflows.json
  catalog/py_package/catalog_build/iwc_manifest_to_workflows_yaml.py
  catalog/source/workflows.yml
Labels: fix

#883 fix: remove analytics text from ga2 subhero text (#874)
  app/components/Home/content/sectionSubHeroGA2.mdx
Labels: fix
