Repository galaxyproject/brc-analytics, pull requests merged in 2025-07, with the labels that each got.

#640 chore: update findable-ui to latest v38.1.1 (#635)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.styles.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSelector/components/Table/table.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.styles.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/PairedEndStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.tsx
  app/components/index.ts
  app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
  app/views/PriorityPathogensView/priorityPathogensView.styles.ts
  app/views/PriorityPathogensView/priorityPathogensView.tsx
  next.config.mjs
  package-lock.json
  package.json
  site-config/brc-analytics/local/config.ts
  site-config/brc-analytics/local/index/genomeEntityConfig.ts
  site-config/brc-analytics/local/index/organismEntityConfig.ts
  site-config/brc-analytics/local/index/priorityPathogensEntityConfig.ts
Labels: chore

#641 feat: link pathogen detail pages priority tag to the organism list filtered by the prioirty (#630)
  app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
Labels: feat

#646 feat: restore hero background on home, about and roadmap pages (#636)
  app/components/Home/components/Section/components/SectionHero/components/Hero/hero.tsx
  app/components/Home/components/Section/components/SectionHero/sectionHero.tsx
  app/components/Layout/components/AppLayout/components/Section/components/SectionHero/components/Hero/hero.styles.ts
  app/components/Layout/components/AppLayout/components/Section/components/SectionHero/components/Hero/hero.tsx
  app/components/Layout/components/AppLayout/components/Section/components/SectionHero/sectionHero.tsx
  app/components/common/Section/section.tsx
Labels: feat

#642 feat: add serotype and isolate info for assemblies
  app/apis/catalog/brc-analytics-catalog/common/entities.ts
  app/components/Home/components/Section/components/SectionViz/NodeDetails.tsx
  app/components/Home/components/Section/components/SectionViz/data.ts
  app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
  catalog/build/intermediate/genomes-from-ncbi.tsv
  catalog/build/intermediate/outbreak-taxonomy-mapping.tsv
  catalog/build/py/build_files_from_ncbi.py
  catalog/build/ts/build-assemblies.ts
  catalog/build/ts/build-organisms.ts
  catalog/build/ts/constants.ts
  catalog/output/assemblies.json
  catalog/output/ncbi-taxa-tree.json
  catalog/output/organisms.json
  catalog/output/outbreaks.json
  catalog/output/qc-report.md
  catalog/py_package/catalog_build/build.py
  catalog/source/organisms.yml
  catalog/source/outbreaks.yml
  site-config/brc-analytics/category.ts
  site-config/brc-analytics/local/index/genomeEntityConfig.ts
  site-config/brc-analytics/local/index/organismEntityConfig.ts
Labels: feat

#599 feat: add IWC linkage from workflows
  app/apis/catalog/brc-analytics-catalog/common/entities.ts
  app/components/Entity/components/AnalysisMethod/components/Workflow/constants.ts
  app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
  catalog/build/ts/build-catalog.ts
  catalog/build/ts/build-workflows.ts
  catalog/output/workflows.json
  catalog/py_package/catalog_build/generated_schema/schema.py
  catalog/py_package/catalog_build/iwc_manifest_to_workflows_yaml.py
  catalog/py_package/catalog_build/schema/workflows.yaml
  catalog/schema/generated/schema.ts
  catalog/schema/generated/workflows.json
  catalog/source/workflows.yml
Labels: feat

#657 fix: allow priority pathogen page scrolling
  app/views/PriorityPathogensView/priorityPathogensView.styles.ts
Labels: fix

#660 feat: add all input parameters to workflows.yml (#653)
  catalog/py_package/catalog_build/iwc_manifest_to_workflows_yaml.py
Labels: feat

#669 chore: update findable-ui to latest version v38.2.0 (#668)
  app/views/PriorityPathogensView/priorityPathogensView.styles.ts
  package-lock.json
  package.json
Labels: chore

#676 feat: remove workflow stepper feature flag
  app/components/Entity/components/AnalysisMethod/analysisMethod.tsx
  app/components/Entity/components/AnalysisMethod/components/Workflow/types.ts
  app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
  app/components/Entity/components/AnalysisMethod/types.ts
  app/components/Entity/components/AnalysisMethodsCatalog/analysisMethodsCatalog.tsx
  pages/_app.tsx
Labels: feat

#683 feat: warnings for failed automagical gtf files
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/gtfStep.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/step.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/LaunchStep/launchStep.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/components/StepWarning/stepWarning.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/hooks/UseLaunchGalaxy/utils.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/utils/stepUtils.ts
Labels: feat

#684 feat: update covid priority pathogen ranking
  catalog/output/assemblies.json
  catalog/output/organisms.json
  catalog/output/outbreaks.json
  catalog/source/outbreaks.yml
Labels: feat

#672 fix: remove unused launchStep.tsx and step.ts (#670)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/LaunchStep/launchStep.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/LaunchStep/step.ts
Labels: fix
