Repository galaxyproject/brc-analytics, pull requests merged in 2025-08, with the labels that each got.

#695 chore: update findable-ui to latest v42.0.1 (#693)
  app/components/Entity/components/AnalysisMethod/analysisMethod.styles.ts
  app/components/Entity/components/AnalysisMethod/analysisMethod.tsx
  app/components/Entity/components/AnalysisMethod/components/Workflow/workflow.tsx
  app/components/Entity/components/AnalysisMethod/constants.ts
  app/components/Entity/components/AnalysisMethodsTitle/analysisMethodsTitle.tsx
  app/components/Entity/components/AnalysisPortals/analysisPortals.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/GTFStep/gtfStep.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/AccessionSelector/accessionSelector.styles.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSummary/collectionSummary.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/DataSelector/dataSelector.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/uploadMyData.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/components/StepError/stepError.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/components/StepWarning/stepWarning.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/stepper.styles.ts
  app/components/Entity/components/Section/KeyValueSection/components/KeyElType/keyElType.tsx
  app/components/Entity/components/Section/KeyValueSection/components/ValueElType/valueElType.tsx
  app/components/Entity/components/Section/MDXSection/mdxSection.styles.ts
  app/components/Entity/components/Section/section.styles.ts
  app/components/Entity/components/Section/section.tsx
  app/components/Home/components/Section/components/SectionAnalytics/components/AnalyticsTools/analyticsTools.styles.ts
  app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.styles.ts
  app/components/Home/components/Section/components/SectionHelp/components/Questions/questions.tsx
  app/components/Home/components/Section/components/SectionHelp/sectionHelp.styles.ts
  app/components/Home/components/Section/components/SectionHero/components/Carousel/carousel.styles.ts
  app/components/Home/components/Section/components/SectionHero/components/Carousel/components/Arrow/arrow.styles.ts
  app/components/Home/components/Section/components/SectionHero/components/Carousel/components/Cards/cards.styles.ts
  app/components/Home/components/Section/components/SectionHero/sectionHero.styles.ts
  app/components/Home/components/Section/components/SectionSubHero/sectionSubHero.styles.ts
  app/components/Home/components/Section/section.styles.ts
  app/components/Layout/components/AppLayout/components/Section/components/SectionHero/sectionHero.styles.ts
  app/components/Layout/components/Footer/components/Branding/branding.styles.ts
  app/components/Layout/components/Footer/components/Branding/branding.tsx
  app/components/Table/table.styles.ts
  app/components/common/Accordion/accordion.styles.ts
  app/components/common/Figure/figure.styles.ts
  app/components/common/Paper/components/FluidPaper/fluidPaper.styles.ts
  app/components/content/content.styles.ts
  app/styles/common/constants/palette.ts
  app/theme/common/components.ts
  app/theme/theme.ts
  app/views/ExploreView/exploreView.styles.ts
  app/views/PriorityPathogenView/components/ResourcesSection/resourcesSection.styles.ts
  app/views/PriorityPathogensView/components/PriorityPathogens/priorityPathogens.styles.ts
  app/views/PriorityPathogensView/components/PriorityPathogens/priorityPathogens.tsx
  app/views/PriorityPathogensView/priorityPathogensView.styles.ts
  app/views/RoadmapView/roadmapView.tsx
  package-lock.json
  package.json
Labels: chore

#717 feat: update column isref to display a chip (#716)
  app/components/index.ts
  app/viewModelBuilders/catalog/brc-analytics-catalog/common/viewModelBuilders.ts
  site-config/brc-analytics/local/index/genomeEntityConfig.ts
Labels: feat

#743 feat: update "upload my data" ui (#741)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/constants.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/uploadMyData.styles.ts
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/UploadMyData/uploadMyData.tsx
Labels: feat

#749 fix: fix sequencing step study accession link (#748)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/viewBuilders.ts
Labels: fix

#774 feat: first version of an organism.yml file for GA2
  catalog/ga2/source/organisms.yml
Labels: feat

#775 chore: update findable-ui to latest v44.0.0 (#770)
  package-lock.json
  package.json
Labels: chore

#776 feat: configure sort by chooser (alpha or count) to filters (#732)
  site-config/brc-analytics/local/config.ts
Labels: feat

#777 feat: configure sort on select sequencing runs table columns (#730)
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/components/ColumnFilters/columnFilters.tsx
  app/components/Entity/components/ConfigureWorkflowInputs/components/Main/components/Stepper/components/Step/SequencingStep/components/ENASequencingData/components/CollectionSelector/hooks/UseTable/hook.ts
Labels: feat
